package br.com.positivo.digitaltwin.core.config;

import lombok.RequiredArgsConstructor;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

@RestController
@RequiredArgsConstructor
public class HomeController {

    private final JdbcTemplate jdbcTemplate;

    @GetMapping(value = "/", produces = MediaType.TEXT_HTML_VALUE)
    public ResponseEntity<String> renderLandingPage() {
        String dbStatus = "DISCONNECTED";
        String dbColor = "#ef4444";
        String dbBadgeBg = "rgba(239, 68, 68, 0.15)";
        
        try {
            jdbcTemplate.queryForObject("SELECT 1", Integer.class);
            dbStatus = "CONNECTED";
            dbColor = "#10b981";
            dbBadgeBg = "rgba(16, 185, 129, 0.15)";
        } catch (Exception ignored) {}

        String now = LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"));

        String html = "<!DOCTYPE html>"
                + "<html lang=\"pt-BR\">"
                + "<head>"
                + "  <meta charset=\"UTF-8\">"
                + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
                + "  <title>Digital Twin API | Positivo Tecnologia</title>"
                + "  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">"
                + "  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>"
                + "  <link href=\"https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700;800&family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap\" rel=\"stylesheet\">"
                + "  <style>"
                + "    * { margin: 0; padding: 0; box-sizing: border-box; }"
                + "    body {"
                + "      background: radial-gradient(circle at 50% 0%, #0f172a 0%, #020617 100%);"
                + "      color: #f8fafc;"
                + "      font-family: 'Plus Jakarta Sans', sans-serif;"
                + "      min-height: 100vh;"
                + "      display: flex;"
                + "      flex-direction: column;"
                + "      align-items: center;"
                + "      justify-content: center;"
                + "      padding: 24px;"
                + "      position: relative;"
                + "      overflow-x: hidden;"
                + "    }"
                + "    .glow {"
                + "      position: absolute;"
                + "      width: 500px;"
                + "      height: 500px;"
                + "      background: radial-gradient(circle, rgba(14, 165, 233, 0.15) 0%, rgba(14, 165, 233, 0) 70%);"
                + "      top: -100px;"
                + "      border-radius: 50%;"
                + "      pointer-events: none;"
                + "    }"
                + "    .card {"
                + "      background: rgba(15, 23, 42, 0.75);"
                + "      backdrop-filter: blur(16px);"
                + "      -webkit-backdrop-filter: blur(16px);"
                + "      border: 1px solid rgba(255, 255, 255, 0.1);"
                + "      border-radius: 24px;"
                + "      padding: 40px;"
                + "      max-width: 620px;"
                + "      width: 100%;"
                + "      box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5), 0 0 40px rgba(14, 165, 233, 0.1);"
                + "      text-align: center;"
                + "      position: relative;"
                + "      z-index: 1;"
                + "    }"
                + "    .badge-live {"
                + "      display: inline-flex;"
                + "      align-items: center;"
                + "      gap: 8px;"
                + "      background: rgba(16, 185, 129, 0.12);"
                + "      border: 1px solid rgba(16, 185, 129, 0.3);"
                + "      color: #34d399;"
                + "      padding: 6px 14px;"
                + "      border-radius: 9999px;"
                + "      font-size: 12px;"
                + "      font-weight: 700;"
                + "      letter-spacing: 0.05em;"
                + "      text-transform: uppercase;"
                + "      margin-bottom: 20px;"
                + "    }"
                + "    .dot {"
                + "      width: 8px;"
                + "      height: 8px;"
                + "      background: #10b981;"
                + "      border-radius: 50%;"
                + "      box-shadow: 0 0 10px #10b981;"
                + "      animation: pulse 2s infinite;"
                + "    }"
                + "    @keyframes pulse {"
                + "      0%, 100% { opacity: 1; transform: scale(1); }"
                + "      50% { opacity: 0.4; transform: scale(0.8); }"
                + "    }"
                + "    h1 {"
                + "      font-family: 'Outfit', sans-serif;"
                + "      font-size: 32px;"
                + "      font-weight: 800;"
                + "      letter-spacing: -0.02em;"
                + "      margin-bottom: 8px;"
                + "      background: linear-gradient(135deg, #ffffff 0%, #cbd5e1 100%);"
                + "      -webkit-background-clip: text;"
                + "      -webkit-text-fill-color: transparent;"
                + "    }"
                + "    p.subtitle {"
                + "      color: #94a3b8;"
                + "      font-size: 15px;"
                + "      margin-bottom: 32px;"
                + "      line-height: 1.5;"
                + "    }"
                + "    .grid-status {"
                + "      display: grid;"
                + "      grid-template-columns: repeat(2, 1fr);"
                + "      gap: 14px;"
                + "      margin-bottom: 32px;"
                + "      text-align: left;"
                + "    }"
                + "    .status-item {"
                + "      background: rgba(30, 41, 59, 0.5);"
                + "      border: 1px solid rgba(255, 255, 255, 0.05);"
                + "      border-radius: 14px;"
                + "      padding: 16px;"
                + "    }"
                + "    .status-item span.label {"
                + "      display: block;"
                + "      font-size: 11px;"
                + "      font-weight: 600;"
                + "      color: #64748b;"
                + "      text-transform: uppercase;"
                + "      letter-spacing: 0.05em;"
                + "      margin-bottom: 4px;"
                + "    }"
                + "    .status-item span.val {"
                + "      font-size: 14px;"
                + "      font-weight: 700;"
                + "      color: #f1f5f9;"
                + "    }"
                + "    .actions {"
                + "      display: flex;"
                + "      gap: 12px;"
                + "      justify-content: center;"
                + "      flex-wrap: wrap;"
                + "    }"
                + "    .btn {"
                + "      display: inline-flex;"
                + "      align-items: center;"
                + "      gap: 8px;"
                + "      padding: 12px 20px;"
                + "      border-radius: 12px;"
                + "      font-size: 13px;"
                + "      font-weight: 600;"
                + "      text-decoration: none;"
                + "      transition: all 0.2s ease;"
                + "    }"
                + "    .btn-primary {"
                + "      background: linear-gradient(135deg, #0ea5e9 0%, #0284c7 100%);"
                + "      color: #ffffff;"
                + "      box-shadow: 0 4px 14px rgba(14, 165, 233, 0.35);"
                + "    }"
                + "    .btn-primary:hover {"
                + "      transform: translateY(-2px);"
                + "      box-shadow: 0 6px 20px rgba(14, 165, 233, 0.5);"
                + "    }"
                + "    .btn-secondary {"
                + "      background: rgba(30, 41, 59, 0.7);"
                + "      border: 1px solid rgba(255, 255, 255, 0.1);"
                + "      color: #cbd5e1;"
                + "    }"
                + "    .btn-secondary:hover {"
                + "      background: rgba(51, 65, 85, 0.7);"
                + "      color: #ffffff;"
                + "      transform: translateY(-2px);"
                + "    }"
                + "    .footer {"
                + "      margin-top: 24px;"
                + "      font-size: 12px;"
                + "      color: #475569;"
                + "    }"
                + "  </style>"
                + "</head>"
                + "<body>"
                + "  <div class=\"glow\"></div>"
                + "  <div class=\"card\">"
                + "    <div class=\"badge-live\"><div class=\"dot\"></div> Sistema Operacional</div>"
                + "    <h1>Plataforma Digital Twin</h1>"
                + "    <p class=\"subtitle\">API REST Oficial de Performance Técnica &mdash; Positivo Tecnologia</p>"
                + "    <div class=\"grid-status\">"
                + "      <div class=\"status-item\">"
                + "        <span class=\"label\">Serviço</span>"
                + "        <span class=\"val\">Spring Boot 3 / Java 21</span>"
                + "      </div>"
                + "      <div class=\"status-item\">"
                + "        <span class=\"label\">Banco de Dados</span>"
                + "        <span class=\"val\" style=\"color: " + dbColor + ";\">" + dbStatus + "</span>"
                + "      </div>"
                + "      <div class=\"status-item\">"
                + "        <span class=\"label\">Horário do Servidor</span>"
                + "        <span class=\"val\">" + now + "</span>"
                + "      </div>"
                + "      <div class=\"status-item\">"
                + "        <span class=\"label\">Arquitetura</span>"
                + "        <span class=\"val\">Modular Monolith</span>"
                + "      </div>"
                + "    </div>"
                + "    <div class=\"actions\">"
                + "      <a href=\"/api/v1/health\" class=\"btn btn-primary\" target=\"_blank\">🩺 Health Check</a>"
                + "      <a href=\"/api/v1/dashboard/version\" class=\"btn btn-secondary\" target=\"_blank\">📊 Info da Versão</a>"
                + "    </div>"
                + "    <div class=\"footer\">&copy; 2026 Positivo Tecnologia &bull; Brilha+ Digital Twin</div>"
                + "  </div>"
                + "</body>"
                + "</html>";

        return ResponseEntity.ok(html);
    }
}
