FROM python:3.10-slim

WORKDIR /app

# Copia e instala a lista completa e oficial de dependências (incluindo PyJWT e pydantic)
COPY ./data_ingestion/ingestion_api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia o código da API de Ingestão
COPY ./data_ingestion/ingestion_api/api_ingestao.py .

CMD ["uvicorn", "api_ingestao:app", "--host", "0.0.0.0", "--port", "8001", "--access-log", "False"]
